const email = 'Email';
const emaihint = 'admin@gmail.com';
const password = 'Password';
const passwordhint = "* * * * * * *";
const forgetPassword = "forgetPassword";
const restartpassword = " Restart password";
const login = "Log In";
const Signup = 'Sign Up';
const SignupDoctor = 'Sign Up Doctor';
const SignupPatint = 'Sign Up Patint';

const CreatedNewAccont = "or,create a new account";
const loginwith = "login with";
const name = 'Name';
const namehint = "admin";
const loggedin = 'logged in Successfully';
const loggedout= 'logged out Successfully';

const singedin = 'singed in Successfully';
const privacyPolicy = ' the privacy policy ';
const termAndCond = 'Terms and Conditions';
const alreadyhaveAcoount = 'Already Have an Account?';
const home = 'Home';
const category = 'Category';
const cart = 'cart';
const account = 'Account';
const search = 'search';
const toDayDeal = 'today is Deal';
const flashsale = 'Flash Sale';
const topSellers = 'top Sellers';
const brand = 'Brand';
const topcategory = 'TopCategories';
const feautercategory = ' Feauter Category';
const weananDress = 'Waman Dress';
const girlWatched = 'girl Watched';
const mobilePhone = 'Mobile Phone';
const boyglasses = 'Boy glasses';
const tshirt = 'tshirt';
const girlDress = 'girl Dress';
const womanClothing = 'woman Cloothing';
const manClothing = 'Man Clothing & fashin';
const computerAccesories = 'Computer Accesories';
const automobile = 'Automobile';
const kittoys = 'Kids & Toys';
const sport = 'Sport';
const jewelery = 'jewelery';
const cellphone = 'CallPhone & Tab';
const furntire = 'Furntire';
const addtocart = 'add to cart';
const video = 'video',
    reviews = 'Reviews',
    sellerPolicy = 'Seller Policy',
    returnPolity = 'Return Policy',
    support = 'support Policy';
const prodectyoutmaybe = 'Peodect Your may also LiKe';
const wishlist = 'My Wishlist', order = 'My Orders', message = 'Messages';
